Feat: wishlist page & cart page
bhtibrewal/Artsy-shop pull request #4
Opened 2022-02-14 16:34 UTC by bhtibrewal

2022-02-15 04:43 UTC, parvez-rashid approved these changes
I have left comments below, have a look. Other than that, code and the preview looks great.

2022-02-15 04:43 UTC, parvez-rashid commented on pages/cart/cart.css
> +  padding: 2rem 5%;
I'm not sure if this is good practice; unless you have a particular purpose here, stick to consistent units.

2022-02-15 04:43 UTC, parvez-rashid commented on style.css
> +.main::-webkit-scrollbar {
You don't need to give browser-specific (`webkit`) styling as it is handled automatically.

2022-02-15 04:43 UTC, parvez-rashid commented on style.css
> +.main::-webkit-scrollbar-thumb{
You don't need to give browser-specific (`webkit`) styling as it is handled automatically.

2022-02-15 04:43 UTC, parvez-rashid commented on style.css
> -::-webkit-scrollbar {
You don't need to give browser-specific (`webkit`) styling as it is handled automatically.

2022-02-15 05:42 UTC, sri-rishi requested changes
![Screenshot (28)](https://user-images.githubusercontent.com/72429483/153999476-6a7af48b-826b-4e81-94fd-880713ed34de.png)


Here button should have remove from wishlist. And just a suggestion comments are not necessary remove them before pushing.

2022-02-15 05:43 UTC, sri-rishi reviewed
Otherwise code looks fine to me

2022-02-15 17:00 UTC, pankaj-prog approved these changes
UI looks good.

2022-02-15 17:00 UTC, pankaj-prog commented on pages/cart/cart.css
> +}
you can improve names here, part1 and part2 is not declarative

2022-02-16 18:19 UTC, bhtibrewal commented on pages/cart/cart.css
> +}
did the changes

2022-02-16 18:20 UTC, merged